name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.8"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.6
            python_version: "3.6"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.8-alpine3.10
            python_version: "3.8"
          - name: python3.7-alpine3.8
            python_version: "3.7"
          - name: python3.6-alpine3.8
            python_version: "3.6"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - name: output date/time in ISO 8601 format
        id: date
        run: echo "::set-output name=iso8601::$(date --iso-8601)"
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get short commit SHA
        id: commit
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker-images
          file: ./docker-images/${{ matrix.image.name }}.dockerfile
          platforms: linux/amd64,linux/arm/v7
          pull: true
          push: true
          tags: |
            ${{ github.repository }}:${{ matrix.image.name }}
            ${{ github.repository }}:${{ matrix.image.name }}-${{ steps.date.outputs.iso8601 }}
